export const credentials = [
  {
    userId: 'rishabhmnnit2@gmail.com',
    password: 'ImdbProject',
    watchList: '[]'
  },
  {
    userId: 'rishabh@gmail.com',
    password: 'rishabh',
    watchList: '[{"vote_count":74,"id":429351,"video":false,"vote_average":5.1,"title":"12 Strong","popularity":142.999487,"poster_path":"/j18021qCeRi3yUBtqd2UFj1c0RQ.jpg","original_language":"en","original_title":"12 Strong","genre_ids":[10752,18,36],"backdrop_path":"/x5EUEv1N9g4BCX9GQXKvv3nqMVo.jpg","adult":false,"overview":"A team of CIA agents and special forces head into Afghanistan in the aftermath of the September 11th attacks in an attempt to dismantle the Taliban.","release_date":"2018-01-18","watchListById":[]},{"vote_count":79,"id":20532,"video":false,"vote_average":8.7,"title":"Sansho the Bailiff","popularity":29.636911,"poster_path":"/deBjt3LT3UQHRXiNX1fu28lAtK6.jpg","original_language":"ja","original_title":"山椒大夫","genre_ids":[18],"backdrop_path":"/keaFMNUr1OpdHzPWJ0qeDP8hrO8.jpg","adult":false,"overview":"In medieval Japan a compassionate governor is sent into exile. His wife and children try to join him, but are separated, and the children grow up amid suffering and oppression.","release_date":"1954-03-31","watchListById":[429351]},{"vote_count":9322,"id":278,"video":false,"vote_average":8.5,"title":"The Shawshank Redemption","popularity":43.12303,"poster_path":"/9O7gLzmreU0nGkIB6K3BsJbzvNv.jpg","original_language":"en","original_title":"The Shawshank Redemption","genre_ids":[18,80],"backdrop_path":"/xBKGJQsAIeweesB79KC89FpBrVr.jpg","adult":false,"overview":"Framed in the 1940s for the double murder of his wife and her lover, upstanding banker Andy Dufresne begins a new life at the Shawshank prison, where he puts his accounting skills to work for an amoral warden. During his long stretch in prison, Dufresne comes to be admired by the other inmates -- including an older prisoner named Red -- for his integrity and unquenchable sense of hope.","release_date":"1994-09-23","watchListById":[429351,20532]},{"vote_count":71,"id":442064,"video":false,"vote_average":5.4,"title":"Proud Mary","popularity":101.691397,"poster_path":"/5luceoVMU2FzWuyty7mZFcSY5ZW.jpg","original_language":"en","original_title":"Proud Mary","genre_ids":[53,28],"backdrop_path":"/6vNh2vkfXVL8PoVXVIeZB6DcwbM.jpg","adult":false,"overview":"A hit woman kills a drug boss only to learn that she has left a boy orphaned. A year later, she saves the boy from a dangerous life on the street but finds herself unable to give the boy or herself a fresh start.","release_date":"2018-01-12","watchListById":[429351,20532,278]}]'
  }
];
